version: '2'
services:
  nginx:
    image: nginx:1.15.5-alpine
    container_name: nginx
    restart: always
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    networks:
      - nginx-net

  keepalived:
    image: osixia/keepalived:1.4.5
    container_name: keepalived
    restart: always
    depends_on:
     - nginx
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    volumes:
     - ./keepalived/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf
     - ./keepalived/check-status.sh:/etc/keepalived/check-status.sh
     - ./keepalived/notify.sh:/container/service/keepalived/assets/notify.sh

networks:
  nginx-net:
    ipam:
      config:
        - subnet: 172.27.2.0/24

