version: '2'
services:
  nginx:
    image: nginx:1.15.5-alpine
    container_name: nginx
    restart: always
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    networks:
      - nginx-net

  keepalived:
    image: osixia/keepalived:2.0.15
    container_name: keepalived
    restart: always
    command: ["--copy-service"]
    depends_on:
      - nginx
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      KEEPALIVED_STATE: ${STATE}
      KEEPALIVED_PRIORITY: ${PRIORITY}
      KEEPALIVED_INTERFACE: ${INTERFACE}
      KEEPALIVED_PASSWORD: ${PASSWORD}
      KEEPALIVED_ROUTER_ID: ${ROUTER_ID}
      KEEPALIVED_UNICAST_PEERS: "#PYTHON2BASH:[${UNICAST_PEERS}]"
      KEEPALIVED_VIRTUAL_IPS: "#PYTHON2BASH:[${VIRTUAL_IPS}]"
    volumes:
      - ./keepalived/keepalived.conf:/container/service/keepalived/assets/keepalived.conf
      - ./keepalived/check-status.sh:/etc/keepalived/check-status.sh

networks:
  nginx-net:
    ipam:
      config:
        - subnet: 172.27.2.0/24

